#!/bin/bash

echo "-------- init ---------"
cleos push action goldencenser init '["alice"]' -p goldencenser@active

echo "-------- load quotes ---------"
cleos push action goldencenser init '["alice"]' -p alice@active
cleos push action goldencenser addquote '["q-00"]' -p alice@active
cleos push action goldencenser addquote '["q-01"]' -p alice@active
cleos push action goldencenser addquote '["q-02"]' -p alice@active
cleos push action goldencenser addquote '["q-03"]' -p alice@active
cleos push action goldencenser addquote '["q-04"]' -p alice@active
cleos push action goldencenser addquote '["q-05"]' -p alice@active
cleos push action goldencenser addquote '["q-06"]' -p alice@active
cleos push action goldencenser addquote '["q-07"]' -p alice@active
cleos push action goldencenser addquote '["q-08"]' -p alice@active
cleos push action goldencenser addquote '["q-09"]' -p alice@active
cleos push action goldencenser addquote '["q-10"]' -p alice@active
cleos push action goldencenser addquote '["q-11"]' -p alice@active
cleos push action goldencenser addquote '["q-12"]' -p alice@active
cleos push action goldencenser addquote '["q-13"]' -p alice@active
cleos push action goldencenser addquote '["q-14"]' -p alice@active
cleos push action goldencenser addquote '["q-15"]' -p alice@active
cleos push action goldencenser addquote '["q-16"]' -p alice@active
cleos push action goldencenser addquote '["q-17"]' -p alice@active
cleos push action goldencenser addquote '["q-18"]' -p alice@active
cleos push action goldencenser addquote '["q-19"]' -p alice@active
cleos push action goldencenser addquote '["q-20"]' -p alice@active
cleos push action goldencenser addquote '["q-21"]' -p alice@active
cleos push action goldencenser addquote '["q-22"]' -p alice@active
cleos push action goldencenser addquote '["q-23"]' -p alice@active
cleos push action goldencenser addquote '["q-24"]' -p alice@active
cleos push action goldencenser addquote '["q-25"]' -p alice@active
cleos push action goldencenser addquote '["q-26"]' -p alice@active
cleos push action goldencenser addquote '["q-27"]' -p alice@active
cleos push action goldencenser addquote '["q-28"]' -p alice@active
cleos push action goldencenser addquote '["q-29"]' -p alice@active
cleos push action goldencenser addquote '["q-30"]' -p alice@active
cleos push action goldencenser addquote '["q-31"]' -p alice@active
cleos push action goldencenser addquote '["q-32"]' -p alice@active
cleos push action goldencenser addquote '["q-33"]' -p alice@active
cleos push action goldencenser addquote '["q-34"]' -p alice@active
cleos push action goldencenser addquote '["q-35"]' -p alice@active
cleos push action goldencenser addquote '["q-36"]' -p alice@active
cleos push action goldencenser addquote '["q-37"]' -p alice@active
cleos push action goldencenser addquote '["q-38"]' -p alice@active
cleos push action goldencenser addquote '["q-39"]' -p alice@active
cleos push action goldencenser addquote '["q-40"]' -p alice@active
cleos push action goldencenser addquote '["q-41"]' -p alice@active
cleos push action goldencenser addquote '["q-42"]' -p alice@active
cleos push action goldencenser addquote '["q-43"]' -p alice@active
cleos push action goldencenser addquote '["q-44"]' -p alice@active
cleos push action goldencenser addquote '["q-45"]' -p alice@active
cleos push action goldencenser addquote '["q-46"]' -p alice@active
cleos push action goldencenser addquote '["q-47"]' -p alice@active
cleos push action goldencenser addquote '["q-48"]' -p alice@active
cleos push action goldencenser addquote '["q-49"]' -p alice@active
cleos push action goldencenser addquote '["q-50"]' -p alice@active
cleos push action goldencenser addquote '["q-51"]' -p alice@active
cleos push action goldencenser addquote '["q-52"]' -p alice@active
cleos push action goldencenser addquote '["q-53"]' -p alice@active
cleos push action goldencenser addquote '["q-54"]' -p alice@active
cleos push action goldencenser addquote '["q-55"]' -p alice@active
cleos push action goldencenser addquote '["q-56"]' -p alice@active
cleos push action goldencenser addquote '["q-57"]' -p alice@active
cleos push action goldencenser addquote '["q-58"]' -p alice@active
cleos push action goldencenser addquote '["q-59"]' -p alice@active
cleos push action goldencenser addquote '["q-60"]' -p alice@active
cleos push action goldencenser addquote '["q-61"]' -p alice@active
cleos push action goldencenser addquote '["q-62"]' -p alice@active
cleos push action goldencenser addquote '["q-63"]' -p alice@active
cleos push action goldencenser addquote '["q-64"]' -p alice@active
cleos push action goldencenser addquote '["q-65"]' -p alice@active
cleos push action goldencenser addquote '["q-66"]' -p alice@active
cleos push action goldencenser addquote '["q-67"]' -p alice@active
cleos push action goldencenser addquote '["q-68"]' -p alice@active
cleos push action goldencenser addquote '["q-69"]' -p alice@active
cleos push action goldencenser addquote '["q-70"]' -p alice@active
cleos push action goldencenser addquote '["q-71"]' -p alice@active
cleos push action goldencenser addquote '["q-72"]' -p alice@active
cleos push action goldencenser addquote '["q-73"]' -p alice@active
cleos push action goldencenser addquote '["q-74"]' -p alice@active
cleos push action goldencenser addquote '["q-75"]' -p alice@active
cleos push action goldencenser addquote '["q-76"]' -p alice@active
cleos push action goldencenser addquote '["q-77"]' -p alice@active
cleos push action goldencenser addquote '["q-78"]' -p alice@active
cleos push action goldencenser addquote '["q-79"]' -p alice@active
cleos push action goldencenser addquote '["q-80"]' -p alice@active
cleos push action goldencenser addquote '["q-81"]' -p alice@active
cleos push action goldencenser addquote '["q-82"]' -p alice@active
cleos push action goldencenser addquote '["q-83"]' -p alice@active
cleos push action goldencenser addquote '["q-84"]' -p alice@active
cleos push action goldencenser addquote '["q-85"]' -p alice@active
cleos push action goldencenser addquote '["q-86"]' -p alice@active
cleos push action goldencenser addquote '["q-87"]' -p alice@active
cleos push action goldencenser addquote '["q-88"]' -p alice@active
cleos push action goldencenser addquote '["q-89"]' -p alice@active
cleos push action goldencenser addquote '["q-90"]' -p alice@active
cleos push action goldencenser addquote '["q-91"]' -p alice@active
cleos push action goldencenser addquote '["q-92"]' -p alice@active
cleos push action goldencenser addquote '["q-93"]' -p alice@active
cleos push action goldencenser addquote '["q-94"]' -p alice@active
cleos push action goldencenser addquote '["q-95"]' -p alice@active
cleos push action goldencenser addquote '["q-96"]' -p alice@active
cleos push action goldencenser addquote '["q-97"]' -p alice@active
cleos push action goldencenser addquote '["q-98"]' -p alice@active
cleos push action goldencenser addquote '["q-99"]' -p alice@active

